[package]
name = "sky_tester"
version = "0.1.0"
authors = ["RipleyTom <RipleyTom@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libusb = "0.3"
